version: '3'
services:
  storitch:
    build: .
    ports:
      - "3000:3000"
    environment:
      - storitch_api_keys=["9dd774ab-869c-47d0-b10e-5a3bf53364bc"]
    volumes:
      - /var/storitch-test:/var/storitch