version: '3'
services:
  storitch:
    build: .
    ports:
      - "3000:3000"
    environment:
      - storitch_api_keys=["test"]
      - storitch_debug=true
    volumes:
      - /var/storitch-test:/var/storitch
      - .:/app